export const PRODUCT_ACTION_TYPES = {
  PRODUCT_LOADING: 'EXPRESS_PRODUCT_LOADING',
  PRODUCT_LOADED: 'EXPRESS_PRODUCT_LOADED',
  PRODUCT_INFO: 'EXPRESS_PRODUCT_INFO',
  ADD_SEASON: 'EXPRESS_ADD_SEASON',
  UPDATE_SEASON: 'EXPRESS_UPDATE_SEASON',
  ADD_SERIYA: 'EXPRESS_ADD_SERIYA',
  UPDATE_SERIYA: 'EXPRESS_UPDATE_SERIYA',
}
