export const PRODUCT_ACTION_TYPES = {
  PRODUCT_LOADING: 'EXPRESS_PRODUCT_LOADING',
  PRODUCT_LOADED: 'EXPRESS_PRODUCT_LOADED',
  SEASON_INFO: 'EXPRESS_SEASON_INFO',
  SEASON_LOADED: 'EXPRESS_PRODUCT_LOADED',
}
